version: "3.9"
services:
  frontend-sample:
    build: 
      context: ./
      dockerfile: Dockerfile.WebApp
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.WebServer
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
     - ~/.aspnet/https:/https:ro